---
- name: setting DMP Develop Environment
  hosts: dev_server
  remote_user: vagrant
  sudo: yes
  gather_facts: no

  roles:
    - selinux
    - yum_repo
    - yum_install
    - mysql
# if you want to use postgresql, remove this comment out instead of mysql.
#    - postgresql
    - git
    - ruby
