---
- name: install mysql
  yum: name={{item}} state=latest
  with_items:
    - mysql-server
    - MySQL-python

- name: start mysql and enabled
  service: name=mysqld state=started enabled=yes

- name: create a database
  mysql_db: name={{ mysql.dbname }} state=present

- name: create a user for db
  mysql_user: name={{ mysql.dbuser }} password={{ mysql.dbpass }} priv=mydb.*:ALL state=present
